### ISSUE TITLE
ROS2

### ISSUE THREAD

**Issue by p0wdrdotcom** [FraunhoferIOSB/camera_aravis#14]
How do the maintainers feel about a port to ROS2?

I would be willing to participate.

**Comment by nznobody** [comment]
I would as well. I started, but it is quite the rabbit hole so I have shelved it for now.

https://github.com/nznobody/camera_aravis/tree/feature/ros2-bones

**Comment by kledom** [comment]
We have a ROS2 version of the package on our agenda, but not with the highest priority. I can't say for sure how long it will take, but hopefully in the near future (~2 months). However, we are always thankful for pull requests, if someone wants to tackle the issue already now.

**Comment by nznobody** [comment]
> I would as well. I started, but it is quite the rabbit hole so I have shelved it for now.
> 
> https://github.com/nznobody/camera_aravis/tree/feature/ros2-bones

Nevermind, this was too much of a task for a quick achievement! A lot of refactoring :(

**Comment by kledom** [comment]
Since the package contains a lot of legacy code, the effort of porting to ROS2 should not be underestimated. Due to missing ROS2 features - namely the missing [SubscriberStatusCallback](https://github.com/ros2/rmw/issues/330) - I have currently paused my efforts until the release of ROS-I.

**Comment by patrikdaniel** [comment]
> Since the package contains a lot of legacy code, the effort of porting to ROS2 should not be underestimated. Due to missing ROS2 features - namely the missing [SubscriberStatusCallback](https://github.com/ros2/rmw/issues/330) - I have currently paused my efforts until the release of ROS 2 Iron Irwini.

ROS 2 Iron Irwini has been [released in May](https://www.openrobotics.org/blog/2023/5/23/ros-2-iron-irwini-released). I'm curious if there are any updates or hints regarding the timeline for porting to ROS 2? It would be great to know when we can expect the transition. Thanks.

**Comment by boitumeloruf** [comment]
Hi... We are currently still quite busy with another project. Soon after that (in 1-2 months) we can again focus on camera_aravis. In the meantime, we welcome any help in porting it to ROS2.

**Comment by patrikdaniel** [comment]
Hi @boitumeloruf, I hope all is well. It's been two months since our last conversation regarding the `camera_aravis` project. I'm curious to know if there have been any updates or changes in its status. Thank you.

**Comment by boitumeloruf** [comment]
Hi @patrikdaniel, sorry for the late reply. Yes, there are updates. We plan to start/continue with porting camera_aravis to ROS2 next week or the week after. I know it is eagerly expected. We are also in need of it, as we are also starting to port our systems to ROS2 soon. Unfortunately, we were held up by other things.

**Comment by ruthvik92** [comment]
Hello,
I am using iDS GigE cameras in my ROS2 Humble based application. I am wondering if I can look forward to use your driver ?

**Comment by boitumeloruf** [comment]
Hi @ruthvik92, yes we have also deployed iDS GigE cameras on our systems. As soon as we have ported the driver to ROS2 you can use it.

**Comment by boitumeloruf** [comment]
Brief information on the topic of porting camera_aravis to ROS2: 

We are currently in the middle of this process. In this, we are refactoring the code quite a bit. Thus, camera_aravis2 will not share the same code base as camera_aravis, which is why we have opted for a new, separate repository. As soon as we have a usable version of camera_aravis2, we will make the repository public and share the information here.

**Comment by patrikdaniel** [comment]
Hi @boitumeloruf, is there any update regarding the release date of `camera_aravis2`? Thanks a lot for your efforts.

**Comment by patrickwasp** [comment]
@patrikdaniel 
It's not a comprehensive package, but while we wait for this one, maybe the demo I prepared could get you started. 
https://github.com/patrickwasp/ros2_aravis_demo

**Comment by boitumeloruf** [comment]
Hi everyone,

we have a beta-version ready in a private repository. Unfortunately, our legal department has to approve the publication of it. Sorry for the delay. I will notify you, as soon as we have made the repository public.

**Comment by patrikdaniel** [comment]
@boitumeloruf, that's great news, thank you!

**Comment by patrikdaniel** [comment]
Hi @boitumeloruf,

Do you have any updates on the approval for publishing the repository?

Thank you!

**Comment by boitumeloruf** [comment]
Hi, 

unfortunately not. We are still waiting for approval. Sorry!

**Comment by boitumeloruf** [comment]
Hello everyone,

I have some good news!  We have now published the repository: https://github.com/FraunhoferIOSB/camera_aravis2
We will soon also release it as an official ROS package.

Please note, that not all features from camera_aravis have yet been implemented. Some features are still on the roadmap. Other features are marked as deprecated. Please have a look into the issue list for more information: https://github.com/FraunhoferIOSB/camera_aravis2/issues

With this, I will close this issue.
