### ISSUE TITLE
Error in streaming video from 2 cameras simultaneously

### ISSUE THREAD

**Issue by mahajanpushkar** [FraunhoferIOSB/camera_aravis#24]
Hi,

I am new to ROS and I want to stream videos from two cameras simultaneously. I am using camera_aravis library and cameras from "The Imaging Source".
When I try to run the first camera using $ rosrun camera_aravis cam_aravis _guid:=<camera name 1>-<serial no. 1>, it works. For second camera I am again using $ rosrun camera_aravis cam_aravis _guid:=<camera name 2>-<serial no. 2> and it works but first one gets shutdown and gives the following messages.

[ WARN] [1671529604.510871557]: Shutdown request received.
[ WARN] [1671529604.510957263]: Reason given for shutdown: [[/camera_aravis] Reason: new node registered with same name]

I changed the name of the node for one camera by using $ rosrun camera_aravis cam_aravis _guid:=<camera name 1>-<serial no. 1> __name:="cam1 and it works. I can use both the cameras for streaming but after some time I get the following:

[ERROR] [1671529153.848003630]: Control to aravis device lost.
[ INFO] [1671529153.850028770]: Completed buffers = 58
[ INFO] [1671529153.850081113]: Failures          = 99
[ INFO] [1671529153.850117464]: Underruns         = 907
[ INFO] [1671529153.850153579]: Resent buffers    = 40086
[ INFO] [1671529153.850186774]: Missing           = 16697

(process:20266): GLib-ERROR **: 10:39:14.376: file ../../../../glib/gthread-posix.c: line 1219 (g_system_thread_wait): error 'Resource deadlock avoided' during 'pthread_join (pt->system_thread, NULL)'
Trace/breakpoint trap (core dumped)

Any leads on how to fix this?

Also, $ roslaunch camera_aravis cam_aravis.launch is detecting 2 cameras but starting/opening only 1 camera. How to start/open both the cameras using launch file alone?

Thank you in advance.

**Comment by boitumeloruf** [comment]
Hi,

to start both cameras from one launch file, adjust the provided launch file by adding another CameraAravisNodelet. Like this, for example:

```
...

<group ns="$(arg sensor_name)">

    <!-- Aravis RGB camera nodelet -->
    <node pkg="nodelet" type="nodelet" name="$(arg sensor_1_name)" args="standalone camera_aravis/CameraAravisNodelet" output="screen">

      <param name="guid"                 value="$(arg sensor_1_serial_no)"/>
      <param name="camera_info_url"      value="$(arg camera_1_info_url)"/>
      <param name="frame_id"             value="$(arg sensor_1_name)"/>

      <param name="publish_tf"           value="true"/>
      <param name="tf_publish_rate"      value="$(arg fps)"/>

      <!-- use GenICam SFNC names as stream control parameters -->
      <param name="PixelFormat"          value="$(arg pixel_format)"/>
      <param name="Width"                value="$(arg width)"/>
      <param name="Height"               value="$(arg height)"/>
      <param name="AcquisitionFrameRate" type="double" value="$(arg fps)"/>

      <param name="Gamma"                value="0.41"/>
      <param name="Gain"                 value="0.0"/>
      <param name="AutoFunctionsROIPreset" value="AutoFunctionsROIPreset_Full"/>
      <param name="ExposureAuto"         value="Continuous"/>
      <param name="GainAuto"             value="Continuous"/>
      <param name="BalanceWhiteAuto"     value="Continuous"/>

    </node>

    <node pkg="nodelet" type="nodelet" name="$(arg sensor_2_name)" args="standalone camera_aravis/CameraAravisNodelet" output="screen">

      <param name="guid"                 value="$(arg sensor_2_serial_no)"/>
      <param name="camera_info_url"      value="$(arg camera_2_info_url)"/>
      <param name="frame_id"             value="$(arg sensor_2_name)"/>

      <param name="publish_tf"           value="true"/>
      <param name="tf_publish_rate"      value="$(arg fps)"/>

      <!-- use GenICam SFNC names as stream control parameters -->
      <param name="PixelFormat"          value="$(arg pixel_format)"/>
      <param name="Width"                value="$(arg width)"/>
      <param name="Height"               value="$(arg height)"/>
      <param name="AcquisitionFrameRate" type="double" value="$(arg fps)"/>

      <param name="Gamma"                value="0.41"/>
      <param name="Gain"                 value="0.0"/>
      <param name="AutoFunctionsROIPreset" value="AutoFunctionsROIPreset_Full"/>
      <param name="ExposureAuto"         value="Continuous"/>
      <param name="GainAuto"             value="Continuous"/>
      <param name="BalanceWhiteAuto"     value="Continuous"/>

    </node>

    ...

  </group>
```

Hope that helps!

**Comment by boitumeloruf** [comment]
Hi @mahajanpushkar,

has my reply answered your question?

I will close the issue now. If the problem still occurs, please feel free to reopen the issue again.
